// =============================================================================
// tcGlobal.cpp - TrussC Global Functions Implementation
//
// Two kinds of definitions live here:
//
//   1. Large lifecycle / frame-management functions moved out of TrussC.h
//      to keep header compile times down (setup, cleanup, present, clear,
//      swapchain pass helpers, ...).
//
//   2. Singletons and accessors that MUST be non-inline so Host (EXE) and
//      Guest (DLL) share a single instance during hot reload on Windows.
//      `inline` functions with static locals create per-module instances
//      under MSVC's per-DLL symbol namespace — splitting events(),
//      getDefaultContext(), timers, the logger, etc. between modules
//      causes silent breakage (drawRectRounded white, tweens frozen, no
//      logs in guest, ...). Moving the definition into this .cpp keeps
//      one canonical instance shared via the host's exported symbols.
//
// When adding a new global singleton accessor, define it here (or in a
// sibling .cpp) rather than inline in a header. tools/check_header_state.py
// (run in CI) fails on new header-inline state; docs/ARCHITECTURE.md, "One
// instance per process", has the rule and the reasons.
// =============================================================================

#include <TrussC.h>

// Generated by sokol-shdc from core/shaders/sglPremult.glsl. Included here (one
// TU) rather than in the widely-included tcRenderTarget.h to avoid pulling the
// generated desc into every translation unit. The shader handle is exposed via
// internal::sglPremultShader().
#include "tc/gpu/shaders/sglPremult.glsl.h"
// Same, from core/shaders/sglCoverage.glsl: internal::sglCoverageShader().
#include "tc/gpu/shaders/sglCoverage.glsl.h"

#ifdef __APPLE__
#include <os/log.h>   // the Logger's platform sink (internal::writeSystemLog)
#endif
#include <cstdlib>

namespace trussc {

// ---------------------------------------------------------------------------
// Initialization (setup)
// ---------------------------------------------------------------------------
void setup() {
    // Initialize sokol_gfx (with memory tracking allocator)
    sg_desc sgdesc = {};
    sgdesc.environment = sglue_environment();
    sgdesc.logger.func = internal::sokolLog;
    // Shader and pipeline pools are fixed at sg_setup(): sg resources point
    // into the pool arrays, so these pools cannot grow (#317). 10000 like the
    // pools below would cost ~34 MB (shader slot ~3.4 KB) and ~12 MB
    // (pipeline slot ~1.2 KB). 1024 shaders (~3.5 MB) leaves room for many
    // loaded Shader objects next to TrussC's own dozen or so. 1024 pipelines
    // (~1.2 MB) is ~200 sgl pipelines (5 sg pipelines each) plus the PBR /
    // point / Shader pipelines per target format.
    sgdesc.shader_pool_size = 1024;   // sokol default 32
    sgdesc.pipeline_pool_size = 1024; // sokol default 64
    sgdesc.buffer_pool_size = 10000;  // default 128 too small with many meshes (only CPU slot table, not GPU memory)
    sgdesc.image_pool_size = 10000;
    sgdesc.view_pool_size = 10000;
    sgdesc.sampler_pool_size = 10000;
    // Per-frame uniform ring buffer (Metal/WebGPU/Vulkan; GL/D3D11 ignore it).
    // On Metal the ring auto-grows on overflow (x2 per step, with a warning log
    // — TrussC patch in sokol_gfx.h), so start small (1MB ≈ 2k draw calls per
    // frame, each apply 256-byte aligned) and let heavy scenes grow to size;
    // WindowSettings::reserveUniformBuffer just skips the one-time grow hitch.
    // WebGPU/Vulkan do NOT auto-grow: keep the 4MB sokol default there — past
    // the cap, RELEASE builds silently write out of bounds (garbage uniforms
    // render as flipped or fully black frames), so high-draw-count apps must
    // reserve enough up front. The backend allocates it x2 in-flight frames.
    if (internal::gpuUniformBufferReserve > 0) {
        sgdesc.uniform_buffer_size = internal::gpuUniformBufferReserve;
    }
    #if defined(SOKOL_METAL)
    else {
        sgdesc.uniform_buffer_size = 1024 * 1024;
    }
    #endif
    sgdesc.allocator.alloc_fn = smemtrack_alloc;
    sgdesc.allocator.free_fn = smemtrack_free;
    sg_setup(&sgdesc);

    // Initialize sokol_gl (with memory tracking allocator)
    sgl_desc_t sgldesc = {};
    sgldesc.logger.func = internal::sokolLog;
    // sgl pipeline slots are small (32 B); the sg pipeline pool above is the
    // real limit, since each sgl pipeline uses 5 sg pipelines. The sgl
    // context pool is left at the sokol_gl_tc.h default: it grows when full.
    sgldesc.pipeline_pool_size = 256;
    sgldesc.max_vertices = internal::sglBudget().maxVertices;
    sgldesc.max_commands = internal::sglBudget().maxCommands;
    sgldesc.allocator.alloc_fn = smemtrack_alloc;
    sgldesc.allocator.free_fn = smemtrack_free;
    sgl_setup(&sgldesc);

    // RenderTarget: the swapchain target uses the default sgl context (carries the
    // swapchain color/depth format + sample count). Pipelines build lazily on first use.
    internal::currentWindowContext().swapchainTarget.context = sgl_default_context();
    internal::currentWindowContext().swapchainTarget.isFbo = false;

    // Initialize bitmap font sampler + pipeline. The atlas TEXTURE itself is
    // allocated lazily on first drawBitmapString call (see ensureFontAtlas in
    // TrussC.h) and grown tier-by-tier as new codepoint ranges are used.
    // Headless apps that never call drawBitmapString pay 0 KB for the atlas.
    auto& fontAtlas = internal::bitmapFontAtlas();
    if (!fontAtlas.initialized) {
        // Sampler (nearest neighbor, pixel perfect)
        sg_sampler_desc smp_desc = {};
        smp_desc.min_filter = SG_FILTER_NEAREST;
        smp_desc.mag_filter = SG_FILTER_NEAREST;
        smp_desc.wrap_u = SG_WRAP_CLAMP_TO_EDGE;
        smp_desc.wrap_v = SG_WRAP_CLAMP_TO_EDGE;
        fontAtlas.sampler = sg_make_sampler(&smp_desc);

        fontAtlas.initialized = true;
    }

    // The 3D / blend-mode / premultiplied / clear pipelines are no longer created
    // here: they are built lazily (and pre-warmed below) by the swapchain
    // RenderTarget, and per-format by each FBO's RenderTarget. See tcRenderTarget.h.

    // Pre-warm the swapchain RenderTarget pipeline cache so active2D/Premult/Clear/3D
    // never create an sgl pipeline mid-frame (lazy creation inside setupScreenFov
    // corrupted the frame; pre-creating here also avoids first-frame hitches).
    internal::active2D(BlendMode::Alpha);
    internal::active2D(BlendMode::Add);
    internal::active2D(BlendMode::Multiply);
    internal::active2D(BlendMode::Screen);
    internal::active2D(BlendMode::Subtract);
    internal::active2D(BlendMode::Disabled);
    internal::activePremult();
    internal::activeCoverage2D();
    internal::activeClear();
    internal::active3D();
}

// ---------------------------------------------------------------------------
// Cleanup (shutdown)
// ---------------------------------------------------------------------------
void cleanup() {
    // The 2D blend / 3D / premultiplied / clear sgl pipelines live in the
    // swapchain and per-FBO RenderTarget caches. sgl pipelines are in one
    // global pool (sgl_destroy_context() frees only the context's own default
    // pipeline); sgl_shutdown() below frees every context and every pipeline,
    // so there is nothing to release individually here. A secondary window
    // frees its own on close() (RenderTarget::release()).

    // Release font resources
    auto& fontAtlas = internal::bitmapFontAtlas();
    if (fontAtlas.initialized) {
        sg_destroy_sampler(fontAtlas.sampler);
        if (fontAtlas.atlasInitialized) {
            sg_destroy_view(fontAtlas.view);
            sg_destroy_image(fontAtlas.texture);
            fontAtlas.atlasInitialized = false;
            fontAtlas.rows = 0;
        }
        fontAtlas.initialized = false;
    }
    sgl_shutdown();
    sg_shutdown();
}

// ---------------------------------------------------------------------------
// Resize sokol_gl buffers (called when vertex/command overflow detected)
// Destroys and recreates sgl only — sg resources (textures, etc.) survive.
// ---------------------------------------------------------------------------
namespace internal {

// Premultiplied-alpha sgl shader (core/shaders/sglPremult.glsl), bound by the
// Screen/Multiply pipelines so their blend equations respect source alpha. Same
// ABI as sgl's built-in shader, so it drops into an sgl pipeline via
// sg_pipeline_desc.shader. Created once on first use (after sokol is up) and
// LEAKED on purpose: a static sg_shader destroyed at __cxa_finalize would call
// sg_destroy after sokol shutdown and crash. It is an sg (not sgl) resource, so
// it survives sgl_shutdown()/resizeSgl() like the font texture. Returns {0} if
// sokol isn't ready yet (caller then falls back to sgl's straight shader).
sg_shader sglPremultShader() {
    static sg_shader shd = {};
    if (shd.id == SG_INVALID_ID && sg_isvalid()) {
        shd = sg_make_shader(tc_sgl_premult_shader_desc(sg_query_backend()));
    }
    return shd;
}

// Coverage sgl shader (core/shaders/sglCoverage.glsl), bound by the
// activeCoverage2D() pipeline that draws the TrueType glyph atlas: the atlas is
// R8 (coverage in R), and this shader uses R as alpha. Same ABI and lifetime as
// sglPremultShader() above. Returns {0} if sokol isn't ready yet.
sg_shader sglCoverageShader() {
    static sg_shader shd = {};
    if (shd.id == SG_INVALID_ID && sg_isvalid()) {
        shd = sg_make_shader(tc_sglcov_coverage_shader_desc(sg_query_backend()));
    }
    return shd;
}

void resizeSgl(int newMaxVertices, int newMaxCommands) {
    auto& budget = sglBudget();
    logNotice("sokol_gl") << "Resizing: vertices " << budget.maxVertices
        << " -> " << newMaxVertices << ", commands " << budget.maxCommands
        << " -> " << newMaxCommands;

    // 1. Shutdown and re-init sokol_gl with larger buffers. sgl_shutdown()
    //    destroys every sgl context and every sgl pipeline (including the
    //    swapchain & FBO RenderTarget caches), so there is nothing to destroy by
    //    hand first.
    //    Font texture/sampler/view are sg resources — they survive sgl_shutdown.
    sgl_shutdown();

    budget.maxVertices = newMaxVertices;
    budget.maxCommands = newMaxCommands;

    sgl_desc_t sgldesc = {};
    sgldesc.logger.func = internal::sokolLog;
    sgldesc.pipeline_pool_size = 256;
    sgldesc.max_vertices = newMaxVertices;
    sgldesc.max_commands = newMaxCommands;
    sgldesc.allocator.alloc_fn = smemtrack_alloc;
    sgldesc.allocator.free_fn = smemtrack_free;
    sgl_setup(&sgldesc);

    // 2. The swapchain RenderTarget's cached pipelines are now stale (their context
    //    was torn down). Drop them and re-warm — the next frame's setupScreenFov
    //    runs every frame and would otherwise create a pipeline mid-frame, which
    //    corrupts the frame (the same reason we pre-warm at setup). Warm against the
    //    swapchain target explicitly in case a resize ever fires outside a swapchain
    //    context.
    internal::currentWindowContext().swapchainTarget.context = sgl_default_context();
    internal::currentWindowContext().swapchainTarget.cache.clear();
    RenderTarget* prevTarget = internal::currentWindowContext().currentTarget;
    internal::currentWindowContext().currentTarget = &internal::currentWindowContext().swapchainTarget;
    active2D(BlendMode::Alpha);
    active2D(BlendMode::Add);
    active2D(BlendMode::Multiply);
    active2D(BlendMode::Screen);
    active2D(BlendMode::Subtract);
    active2D(BlendMode::Disabled);
    activePremult();
    activeCoverage2D();
    activeClear();
    active3D();
    internal::currentWindowContext().currentTarget = prevTarget;
    // NOTE: each FBO's RenderTarget cache (and its sgl context) is also invalidated
    // by sgl_shutdown but is NOT rebuilt here — FBOs surviving an sgl buffer resize
    // is a pre-existing limitation, out of scope for this refactor.

    budget.pendingResize = 0;
}
} // namespace internal

// ---------------------------------------------------------------------------
// Clear screen (RGB float: 0.0 ~ 1.0)
// Works correctly in FBO or during swapchain pass (oF compatible)
// ---------------------------------------------------------------------------
namespace {
// Record an opaque fullscreen quad (activeClear pipeline) into the CURRENT
// sokol_gl layer — clear()'s erase semantics on the swapchain (issue #190).
// Deferred shader/PBR/point draws recorded before this stay in earlier layers
// (behind the quad); later ones composite on top. The quad is drawn at the
// far plane with depth compare ALWAYS + write enabled (pipeDescClear), so it
// also resets the depth buffer: 3D drawn after the clear() is not occluded by
// pre-clear 3D geometry. sgl just records — this works with or without an
// active render pass.
void recordSwapchainClearQuad(float r, float g, float b, float a) {
    BlendMode prevBlendMode = internal::currentWindowContext().currentBlendMode;

    sgl_push_matrix();
    sgl_matrix_mode_projection();
    sgl_push_matrix();

    internal::sglLoadProjection(internal::toBackendClip(
        Mat4::ortho(-1.0f, 1.0f, 1.0f, -1.0f, -1.0f, 1.0f)));
    sgl_matrix_mode_modelview();
    sgl_load_identity();

    internal::loadPipeline(internal::activeClear());
    sgl_disable_texture();
    sgl_begin_quads();
    sgl_c4f(r, g, b, a);
    // z = -1 maps through the GL-convention ortho above (z_ndc = -z) to the
    // far plane; toBackendClip remaps to the backend's depth range.
    sgl_v3f(-1.0f, -1.0f, -1.0f);
    sgl_v3f( 1.0f, -1.0f, -1.0f);
    sgl_v3f( 1.0f,  1.0f, -1.0f);
    sgl_v3f(-1.0f,  1.0f, -1.0f);
    sgl_end();

    sgl_matrix_mode_projection();
    sgl_pop_matrix();
    sgl_matrix_mode_modelview();
    sgl_pop_matrix();

    internal::loadPipeline(internal::active2D(prevBlendMode));
}
} // anonymous namespace

void clear(float r, float g, float b, float a /* = 1.0f */) {
    // Skip in headless mode (no graphics context)
    if (headless::isActive()) return;

    auto& ctx = internal::currentWindowContext();
    if (ctx.inFboPass && ctx.fboClearColorFunc) {
        // During FBO pass, call FBO's clearColor() to restart pass
        ctx.fboClearColorFunc(r, g, b, a);
    } else if (ctx.inSwapchainPass) {
        // During swapchain pass: erase by recording an opaque fullscreen quad
        recordSwapchainClearQuad(r, g, b, a);
    } else {
        // Outside a pass. If nothing has been recorded for the swapchain yet
        // this frame, keep the cheap path: stash the clear color as the pass
        // CLEAR action, consumed when the pass starts in ensureSwapchainPass()
        // (the normal clear()-at-top-of-draw() pattern costs nothing extra).
        // Otherwise clear() must ERASE what came before (issue #190): record
        // the opaque fullscreen quad in submission order instead.
        //
        // "Something recorded" = any sokol_gl vertices in the current
        // (swapchain) context this frame (sgl_num_vertices is per context and
        // rewinds on sg_commit), any deferred shader / PBR / point draws, or
        // a swapchain pass that already ran this frame (e.g. FullscreenShader
        // drew directly and an FBO suspended the pass — that drawable content
        // survives the resume via LOAD, see #191, so it must be erased too).
        bool hasRecorded = sgl_num_vertices() > 0
            || !ctx.deferredShaderDraws.empty()
            || !ctx.deferredPbrDraws.empty()
            || !ctx.deferredPointDraws.empty()
            || ctx.swapchainPassStartedThisFrame;
        if (hasRecorded) {
            recordSwapchainClearQuad(r, g, b, a);
        } else {
            // sgl commands accumulate without an active pass, so FBOs can
            // render in their own passes without interrupting the swapchain
            // pass; the swapchain pass itself starts in present().
            ctx.swapchainClearValue = { r, g, b, a };
        }
    }
}

// ---------------------------------------------------------------------------
// パス管理関数（non-inline: Hot Reload時にHost/Guest間で同じ状態を参照するため）
// ---------------------------------------------------------------------------
namespace {
// Start (or restart) the swapchain render pass for the current window.
// The FIRST start of a frame clears color and depth with swapchainClearValue
// (frame background). Any subsequent start — resumeSwapchainPass() after an
// FBO / shadow / reflection pass suspended it — must LOAD color AND depth so
// everything already rendered into the drawable this frame survives (issue
// #191: FullscreenShader/direct-pass content was wiped by the old
// unconditional CLEAR).
// `preserveContents` marks a pass that may be suspended and resumed later in
// the same frame (any pass started OUTSIDE present(): FullscreenShader / LUT
// force-starts, resumes after Fbo / shadow / reflection passes). Such passes
// set depth.store_action = SG_STOREACTION_STORE, which does double duty:
//   - stores the depth buffer so the resume can LOAD it (upstream sokol
//     discards swapchain depth after every pass), and
//   - on Metal + MSAA it is the hint (see the [TrussC] patch in sokol_gfx.h)
//     to store the multisample texture, which upstream resolve-only passes
//     discard — without it a resumed pass would LOAD undefined content.
// The final pass started in present() passes false, so the normal
// clear-at-top-of-draw() frame keeps today's exact store behavior (resolve-
// only color, discarded depth) — zero bandwidth regression.
void beginSwapchainPassInternal(bool preserveContents) {
    auto& ctx = internal::currentWindowContext();
    sg_pass pass = {};
    if (!ctx.swapchainPassStartedThisFrame) {
        pass.action.colors[0].load_action = SG_LOADACTION_CLEAR;
        pass.action.colors[0].clear_value = ctx.swapchainClearValue;
        pass.action.depth.load_action = SG_LOADACTION_CLEAR;
        pass.action.depth.clear_value = 1.0f;
    } else {
        pass.action.colors[0].load_action = SG_LOADACTION_LOAD;
        pass.action.depth.load_action = SG_LOADACTION_LOAD;
    }
    if (preserveContents) {
        pass.action.depth.store_action = SG_STOREACTION_STORE;
    }
    // Secondary windows provide their own swapchain (same drawable for the
    // whole window frame); the main window uses sokol_glue as before.
    pass.swapchain = ctx.acquireSwapchain ? ctx.acquireSwapchain(ctx.acquireSwapchainUser)
                                          : sglue_swapchain();
    // Record the drawable we render into so end-of-frame capture reads back
    // THIS one (sapp_get_swapchain() advances the Metal drawable per call).
    ctx.lastSwapchainDrawable = pass.swapchain.metal.current_drawable;
    // Record the whole swapchain too: the Windows / Linux capture backends read
    // this window's render_view / gl.framebuffer + size from here (mac uses the
    // drawable above). Main window: this is sglue_swapchain(), i.e. identical to
    // sapp_get_swapchain(), so the main capture path is unchanged.
    ctx.lastSwapchain = pass.swapchain;
    sg_begin_pass(&pass);
    ctx.inSwapchainPass = true;
    ctx.swapchainPassStartedThisFrame = true;
}
} // anonymous namespace

void ensureSwapchainPass() {
    if (!internal::currentWindowContext().inSwapchainPass && !internal::currentWindowContext().inFboPass) {
        // Callers outside present() (FullscreenShader, tcxLut, ...) force-start
        // the pass mid-frame; it may be suspended by an Fbo/shadow pass later,
        // so its contents must be preserved.
        beginSwapchainPassInternal(true);
    }
}

namespace internal {
OnceGate& sglStackErrorReportGate(bool inFbo) {
    if (inFbo) {
        static OnceGate gate{5.0};
        return gate;
    }
    static OnceGate gate{5.0};
    return gate;
}

void reportSglStackErrors(sgl_error_t err, bool inFbo) {
    // Matrix stack errors (#232): TrussC keeps its push/pop balanced per node
    // and per frame. FBO contexts are reset at begin() (#327). Reported once, then
    // at most every 5 s per place — the flags are cleared again at sg_commit().
    if (err.stack_overflow || err.stack_underflow) {
        if (sglStackErrorReportGate(inFbo).isFirstTime()) {
            logWarning("sokol_gl") << "matrix stack "
                << (err.stack_overflow ? "overflow (more than 64 nested pushMatrix / node levels in one frame)"
                                       : "underflow (sgl_pop_matrix without a push)")
                << (inFbo ? " in an Fbo pass" : " on screen")
                << "; transforms past that point are wrong this frame";
        }
    }
}
} // namespace internal

void present() {
    if (headless::isActive()) return;

    // Final pass of the frame — nothing suspends it, so no preserve hint
    // (keeps the normal one-pass frame's store behavior unchanged).
    if (!internal::currentWindowContext().inSwapchainPass && !internal::currentWindowContext().inFboPass) {
        beginSwapchainPassInternal(false);
    }

    internal::flushDeferredShaderDraws();

    events().onRender.notify();

    sgl_error_t err = sgl_error();
    internal::reportSglStackErrors(err, false);
    if (err.vertices_full || err.commands_full) {
        auto& budget = internal::sglBudget();
        int newVerts = budget.maxVertices * 4;
        if (newVerts > budget.pendingResize) {
            budget.pendingResize = newVerts;
            logNotice("sokol_gl") << "Vertex buffer overflow detected ("
                << budget.maxVertices << " vertices, "
                << budget.maxCommands << " commands). "
                << "Will resize to " << newVerts << " next frame.";
        }
    }

    sg_end_pass();
    internal::currentWindowContext().inSwapchainPass = false;
    // Frame is over: the next swapchain pass start belongs to the next frame
    // and must CLEAR again with swapchainClearValue (see issue #191).
    internal::currentWindowContext().swapchainPassStartedThisFrame = false;
    sg_commit();

    // Now that every deferred draw (swapchain layers above, FBO passes at
    // their Fbo::end()) has been submitted, it is safe to destroy the GPU
    // resources released during this frame (temporary Mesh draws, texture
    // re-uploads, atlas growth, sampler changes, ...).
    internal::drainPendingGpuDestroys();

    // Frame end (#232): whatever this frame left pushed is dropped here (with
    // a warning), so a missing pop can't leak into the next frame; sokol_gl's
    // matrix stacks go back to depth 0 with it. Done here because present()
    // is each window's last call of the frame — not in beginFrame(), which
    // EasyCam::end() also calls mid-frame to return to 2D.
    internal::getDefaultContext().resetStacksAtFrameEnd();
    sgl_tc_reset_matrix_stacks();
}

bool isInSwapchainPass() {
    return internal::currentWindowContext().inSwapchainPass;
}

void suspendSwapchainPass() {
    if (internal::currentWindowContext().inSwapchainPass) {
        sg_end_pass();
        internal::currentWindowContext().inSwapchainPass = false;
    }
}

void resumeSwapchainPass() {
    if (!internal::currentWindowContext().inSwapchainPass) {
        // Restart uses LOAD when the pass already ran this frame — see
        // beginSwapchainPassInternal() (issue #191). A resumed pass may be
        // suspended again (multiple Fbo blocks), so preserve its contents too.
        beginSwapchainPassInternal(true);
    }
}

// ---------------------------------------------------------------------------
// Non-inline singletons / accessors (Hot Reload: Host/Guest share state)
// ---------------------------------------------------------------------------

namespace internal {
namespace {
// Main-thread-only lighting cleanup can outlive these function-local statics
// (e.g. a sketch's global Material). Constant initialization and trivial
// destruction keep the flag readable throughout static destruction.
constinit bool windowStateDestroyed = false;

struct WindowStateLifetimeMark {
    ~WindowStateLifetimeMark() { windowStateDestroyed = true; }
};
} // namespace

// The main window's state container. Non-inline so a hot-reload guest binds
// to the host's instance (same pattern as events()/getDefaultContext()).
WindowContext& mainWindowContext() {
    static WindowContext ctx;
    // Destroyed before ctx, like LoggerLifetimeMark below.
    static WindowStateLifetimeMark lifetimeMark;
    (void)lifetimeMark;
    return ctx;
}

// Open-window registry (see tcWindow.h). Non-inline for the same host/guest
// reason as mainWindowContext(). Main thread only.
static std::vector<Window*>& windowRegistryStorage() {
    static std::vector<Window*> list;
    // Either storage may be initialized first; stop cleanup before either dies.
    static WindowStateLifetimeMark lifetimeMark;
    (void)lifetimeMark;
    return list;
}
void registerWindow(Window* w) {
    windowRegistryStorage().push_back(w);
}
void unregisterWindow(Window* w) {
    auto& list = windowRegistryStorage();
    list.erase(std::remove(list.begin(), list.end(), w), list.end());
}
WindowOccludedHook& windowOccludedHookForTests() {
    static WindowOccludedHook hook = nullptr;
    return hook;
}
std::vector<Window*> openWindows() {
    std::vector<Window*> out;
    for (Window* w : windowRegistryStorage()) {
        if (w && w->isOpen()) out.push_back(w);
    }
    return out;
}

// Unregister a destroyed Light from every window context's activeLights, so a
// still-registered Light never dangles (the PBR pipeline derefs those pointers
// every lit draw — issue: ~Light() had no cleanup). Called by ~Light()
// (declared in tcLight.h); defined here because it needs the Window registry.
// Non-inline keeps it host/guest-shared under hot reload, same as the registry.
void removeLightFromAllContexts(Light* light) {
    if (windowStateDestroyed) return;
    auto scrub = [&](WindowContext& ctx) {
        auto& v = ctx.activeLights;
        v.erase(std::remove(v.begin(), v.end(), light), v.end());
    };
    scrub(mainWindowContext());
    for (Window* w : openWindows()) {
        if (w) scrub(w->context());
    }
}

// Detach destroyed lighting state before the next mesh draw. Like Light's
// cleanup, these definitions are shared by the hot-reload host and guest.
void clearMaterialFromAllContexts(Material* material) {
    if (windowStateDestroyed) return;
    auto scrub = [&](WindowContext& ctx) {
        if (ctx.currentMaterial == material) ctx.currentMaterial = nullptr;
    };
    scrub(mainWindowContext());
    for (Window* w : openWindows()) {
        if (w) scrub(w->context());
    }
}

void clearEnvironmentFromAllContexts(Environment* environment) {
    if (windowStateDestroyed) return;
    auto scrub = [&](WindowContext& ctx) {
        if (ctx.currentEnvironment == environment) ctx.currentEnvironment = nullptr;
    };
    scrub(mainWindowContext());
    for (Window* w : openWindows()) {
        if (w) scrub(w->context());
    }
}

// Declared in tcWindowContext.h. Every registered window, not only the open
// ones: a closed Window the app still holds keeps its context, and with it
// the hover / grab / selection it had when it closed.
void resetNodeRefsForUnload() {
    auto reset = [](WindowContext& ctx) {
        ctx.hoveredNode.reset();
        ctx.prevHoveredNode.reset();
        ctx.grabbedNode.reset();
        ctx.grabbedButton = -1;
        ctx.selectedNode.reset();
    };
    reset(mainWindowContext());
    mainWindowContext().rootNode.reset();
    for (Window* w : windowRegistryStorage()) {
        if (w) reset(w->context());
    }
}
} // namespace internal

CoreEvents& events() {
    // The CoreEvents instance is owned per window context. The main window's
    // is wired lazily here (preserving the pre-context construction timing);
    // Phase 1 pre-wires the pointer when constructing secondary contexts.
    auto& ctx = internal::currentWindowContext();
    if (!ctx.coreEvents) {
        static CoreEvents instance;   // main-window storage
        ctx.coreEvents = &instance;
    }
    return *ctx.coreEvents;
}

// ---------------------------------------------------------------------------
// Elapsed-time clock (#229) — see tcTime.h for the design.
// ---------------------------------------------------------------------------
namespace {
// steady_clock, not high_resolution_clock: on libstdc++ the latter is
// system_clock, which follows NTP steps and manual clock changes.
std::chrono::steady_clock::time_point clockOrigin() {
    static const std::chrono::steady_clock::time_point origin =
        std::chrono::steady_clock::now();
    return origin;
}
// Take the origin during static initialization, i.e. at program start, so
// "elapsed since program start" holds whether or not anything reads the
// clock early. (A read from another TU's static initializer that runs first
// just takes it a little earlier; the function-local static makes that safe.)
[[maybe_unused]] const bool clockOriginTaken = (clockOrigin(), true);

// Display offset for resetElapsedTimeCounter(), in steady_clock ticks.
// Atomic: the elapsed getters may be called from worker threads.
std::atomic<std::chrono::steady_clock::rep> elapsedTimeOffsetTicks{0};
} // namespace

namespace internal {
std::chrono::steady_clock::duration getUptime() {
    return std::chrono::steady_clock::now() - clockOrigin();
}

std::chrono::steady_clock::duration getElapsedTimeOffset() {
    return std::chrono::steady_clock::duration(
        elapsedTimeOffsetTicks.load(std::memory_order_relaxed));
}

void setElapsedTimeOffset(std::chrono::steady_clock::duration offset) {
    elapsedTimeOffsetTicks.store(offset.count(), std::memory_order_relaxed);
}

void sampleFrameTime(WindowContext& ctx) {
    ctx.frameUptime = getUptime();
    ctx.frameUptimeSampled = true;
}

void recordUpdateRateSample(WindowContext& ctx, double duration, double steps) {
    if (!(duration >= 0.0)) return;   // also rejects NaN
    if (!(steps >= 0.0)) steps = 0.0;
    ctx.rateDurations[ctx.rateIndex] = duration;
    ctx.rateSteps[ctx.rateIndex] = steps;
    ctx.rateIndex = (ctx.rateIndex + 1) % WindowContext::rateSampleCount;
    if (ctx.rateCount < WindowContext::rateSampleCount) ctx.rateCount++;
}

std::chrono::steady_clock::time_point getUpdateTime() {
    return currentWindowContext().updateTime;
}

bool isInUpdate() {
    return currentWindowContext().inUpdate;
}

bool isFixedStepUpdate() {
    return currentWindowContext().fixedStepUpdate;
}

// ---------------------------------------------------------------------------
// Loop timing helpers (tcFrameTiming.h)
// ---------------------------------------------------------------------------
FixedStepAdvance advanceFixedStep(double& accumulator, double elapsed,
                                  double interval, int maxSteps) {
    FixedStepAdvance r;
    if (!(interval > 0.0) || !std::isfinite(interval)) return r;
    if (elapsed > 0.0 && std::isfinite(elapsed)) accumulator += elapsed;
    const int cap = maxSteps > 0 ? maxSteps : std::numeric_limits<int>::max();
    while (r.steps < cap && accumulator >= interval) {
        accumulator -= interval;
        ++r.steps;
    }
    if (accumulator >= interval) {
        // Over the cap: drop whole intervals, keep the fractional phase.
        double keep = std::fmod(accumulator, interval);
        r.droppedTime = accumulator - keep;
        accumulator = keep;
    }
    return r;
}

double headlessSleepTime(double accumulator, double interval, double spent) {
    if (!(interval > 0.0) || !std::isfinite(interval)) return headlessMaxSleepTime;
    if (!(spent > 0.0) || !std::isfinite(spent)) spent = 0.0;
    const double untilDue = interval - accumulator - spent;
    if (!(untilDue > 0.0)) return 0.0;
    return untilDue < headlessMaxSleepTime ? untilDue : headlessMaxSleepTime;
}

#if defined(_WIN32) && !defined(CREATE_WAITABLE_TIMER_HIGH_RESOLUTION)
#define CREATE_WAITABLE_TIMER_HIGH_RESOLUTION 0x00000002   // Windows SDK 10.0.17134+
#endif

HeadlessSleeper::HeadlessSleeper() {
#ifdef _WIN32
    // nullptr before Windows 10 1803, which rejects the flag.
    timer_ = CreateWaitableTimerExW(nullptr, nullptr, CREATE_WAITABLE_TIMER_HIGH_RESOLUTION,
                                    TIMER_MODIFY_STATE | SYNCHRONIZE);
#endif
}

HeadlessSleeper::~HeadlessSleeper() {
#ifdef _WIN32
    if (timer_) CloseHandle((HANDLE)timer_);
#endif
}

void HeadlessSleeper::sleep(double seconds) {
    if (!(seconds > 0.0)) {
        std::this_thread::yield();
        return;
    }
    if (seconds > 1.0) seconds = 1.0;
#ifdef _WIN32
    if (timer_) {
        LARGE_INTEGER due;
        due.QuadPart = -(LONGLONG)std::ceil(seconds * 1e7);   // relative, 100 ns units
        if (SetWaitableTimer((HANDLE)timer_, &due, 0, nullptr, nullptr, FALSE) &&
            WaitForSingleObject((HANDLE)timer_, INFINITE) == WAIT_OBJECT_0) {
            return;
        }
    }
#endif
    std::this_thread::sleep_for(std::chrono::nanoseconds((long long)std::ceil(seconds * 1e9)));
}

bool frameSkipShouldTick(double& accumulator, double elapsed, double interval) {
    if (!(interval > 0.0) || !std::isfinite(interval)) return true;
    if (!(elapsed > 0.0) || !std::isfinite(elapsed)) elapsed = 0.0;
    accumulator += elapsed;
    if (accumulator + 0.5 * elapsed < interval) return false;
    accumulator -= interval;
    if (accumulator > interval) {
        accumulator = 0.0;             // long stall: don't burst-catch-up
    } else if (accumulator < -interval) {
        accumulator = -interval;
    }
    return true;
}

void warnUpdateStepsDropped(FixedStepLoop loop, double droppedTime, double interval,
                            int stepsRun) {
    // One flag per loop: each loop reports its own first drop.
    static std::atomic<bool> warned[2] = {false, false};
    const bool headless = (loop == FixedStepLoop::Headless);
    if (warned[headless ? 1 : 0].exchange(true)) return;
    const char* where = headless ? "Headless loop" : "Update loop";
    const char* frame = headless ? "loop pass" : "frame";
    // stepsRun is the cap (getMaxUpdateSteps()): time is only dropped once
    // the cap is reached. The main loop steps once per frame callback, so a
    // rate above that many times the display rate can't keep up either. The
    // headless loop sleeps only until its next step is due, so on its own it
    // falls behind only when one OS sleep overshoots by that many steps.
    auto warning = logWarning("Loop");
    warning << where << " fell behind its fixed rate: ran "
        << stepsRun << " update steps in one " << frame << " and dropped "
        << droppedTime << " s (" << (interval > 0.0 ? droppedTime / interval : 0.0)
        << " steps at " << (interval > 0.0 ? 1.0 / interval : 0.0)
        << " Hz) instead of replaying it. The app stalled, or update() is too slow "
           "for this rate";
    if (headless) {
        warning << ", or the rate is so high that one OS sleep spans more than "
            << stepsRun << " steps";
    } else {
        warning << ", or the update rate is more than " << stepsRun
            << "x the display's frame rate";
    }
    warning << ". setMaxUpdateSteps() sets the cap (0 = run every step). Logged once.";
}
} // namespace internal

// ---------------------------------------------------------------------------
// Update step cap of the fixed-step loops (setMaxUpdateSteps, #228). Stored
// here, not inline in a header, so the hot-reload Host and Guest share it.
// ---------------------------------------------------------------------------
namespace {
std::atomic<int> maxUpdateSteps{10};
} // namespace

void setMaxUpdateSteps(int steps) {
    maxUpdateSteps.store(steps, std::memory_order_relaxed);
}

int getMaxUpdateSteps() {
    return maxUpdateSteps.load(std::memory_order_relaxed);
}

double getElapsedTime() {
    return std::chrono::duration<double>(internal::getElapsedDuration()).count();
}

double getFrameElapsedTime() {
    auto& ctx = internal::currentWindowContext();
    // Before this window's first frame (e.g. during a window's own setup),
    // and in secondary windows, whose platform tick doesn't sample it yet
    // (the multi-window work that follows #219), fall back to the live clock.
    if (!ctx.frameUptimeSampled) return getElapsedTime();
    auto d = ctx.frameUptime - internal::getElapsedTimeOffset();
    if (d.count() < 0) return 0.0;
    return std::chrono::duration<double>(d).count();
}

// getFrameCount()/getUpdateCount() resolve through the CURRENT window context.
// The main window keeps returning internal::updateFrameCount — bit-identical to
// the old global, and the value the hot-reload host mirrors (tcHotReloadHost.h)
// — while a secondary window returns its own per-tick counter (advanced in the
// native windowTick before update()). Single-window apps are unaffected.
uint64_t getUpdateCount() {
    auto& ctx = internal::currentWindowContext();
    return ctx.isMain ? internal::updateFrameCount : ctx.updateCount;
}

// Device/main-window frame count. Left on sapp_frame_count(): it is the
// sokol_app frame index used for one-update-per-device-frame guards, not a
// per-window update counter (secondary draws happen within main-thread ticks
// and are not tracked separately).
uint64_t getDrawCount() {
    return sapp_frame_count();
}

uint64_t getFrameCount() {
    auto& ctx = internal::currentWindowContext();
    return ctx.isMain ? internal::updateFrameCount : ctx.updateCount;
}

double getDeltaTime() {
    // Per-window: inside a secondary window's update/draw this is that
    // window's own tick delta, not the main window's.
    return internal::currentWindowContext().updateDeltaTime;
}

double getFrameRate() {
    // Measured update rate over the last few frames: update steps divided by
    // the wall time they covered. Recorded by the main and headless loops
    // (recordUpdateRateSample), so reading it has no side effects. In fixed-Hz
    // update mode this is the MEASURED rate, not the configured one (#228):
    // the fixed-step loops count the time their steps consumed (fractional
    // steps), so a rate that isn't a multiple of the frame rate reads steady,
    // and dropped time lowers it.
    auto& ctx = internal::currentWindowContext();
    if (!ctx.isMain) {
        // A secondary window's platform tick records no rate samples yet (the
        // multi-window work that follows #219): average the last 10 deltas
        // read here, as before.
        double dt = ctx.updateDeltaTime;
        if (dt <= 0.0) return 0.0;
        ctx.frameTimeBuffer[ctx.frameTimeIndex] = dt;
        ctx.frameTimeIndex = (ctx.frameTimeIndex + 1) % 10;
        if (ctx.frameTimeIndex == 0) {
            ctx.frameTimeBufferFilled = true;
        }

        int count = ctx.frameTimeBufferFilled ? 10 : ctx.frameTimeIndex;
        if (count == 0) return 0.0;

        double sum = 0.0;
        for (int i = 0; i < count; i++) {
            sum += ctx.frameTimeBuffer[i];
        }
        double avgDt = sum / count;
        return avgDt > 0.0 ? 1.0 / avgDt : 0.0;
    }
    double time = 0.0;
    double steps = 0.0;
    for (int i = 0; i < ctx.rateCount; i++) {
        time += ctx.rateDurations[i];
        steps += ctx.rateSteps[i];
    }
    return time > 0.0 ? steps / time : 0.0;
}

namespace {
// Set during static destruction, right before getLogger()'s Logger is
// destroyed. Constant-initialized and trivially destructible, so it can be
// read at any point of static destruction.
std::atomic<bool> loggerDestroyed{false};

struct LoggerLifetimeMark {
    ~LoggerLifetimeMark() { loggerDestroyed.store(true); }
};
} // namespace

Logger& getLogger() {
    static Logger logger;
    // Constructed after logger, so destroyed right before it.
    static LoggerLifetimeMark lifetimeMark;
    (void)lifetimeMark;
    return logger;
}

// Shared by the deferred queue, native file writers and MCP path reporting.
std::filesystem::path internal::resolveScreenshotPath(const std::filesystem::path& path) {
    auto resolved = path.is_absolute() ? path : getDataPath(path);
    const auto ext = toLower(getFileExtension(resolved));
    const bool common = ext == "png" || ext == "jpg" || ext == "jpeg" || ext == "bmp";
    const bool mac = Platform::isMacOS() &&
                     (ext == "tiff" || ext == "tif" || ext == "gif");
    const bool win = Platform::isWindows() && ext == "tga";
    if (!common && !mac && !win) {
        resolved += ".png";
        const char* formats = Platform::isMacOS() ? "png, jpg/jpeg, bmp, tiff/tif, gif" :
                              Platform::isWindows() ? "png, jpg/jpeg, bmp, tga" :
                                                      "png, jpg/jpeg, bmp";
        logWarning("Screenshot") << "Unsupported or missing extension; saving PNG to "
                                 << internal::pathToUtf8(resolved) << ". Supported formats: " << formats;
    }
    return resolved;
}

// Declared in tcLog.h. Defined here because tcLog.h cannot include tcUtils.h
// (getDataPath): tcUtils.h includes tcSound.h, which includes tcLog.h.
bool Logger::setLogFile(const fs::path& path) {
    // Relative paths resolve against the data folder, like every other writer.
    // An absolute path skips getDataPath(), so it never reads the data path
    // state (unlocked, and written by the first call on Apple).
    const fs::path resolved = path.is_absolute() ? path : getDataPath(path);
    const std::string pathUtf8 = internal::pathToUtf8(resolved);

    // "" or "logs/": fail before creating any folder (the current log stays
    // open, as with the failures below).
    if (resolved.filename().empty()) {
        log(LogLevel::Error, "Failed to open log file: " + pathUtf8 + " (no file name in path)");
        return false;
    }

    // Create a missing parent folder, like saveScreenshot().
    std::error_code ec;
    const fs::path parent = resolved.parent_path();
    if (!parent.empty()) {
        fs::create_directories(parent, ec);
        if (ec) {
            log(LogLevel::Error, "Failed to open log file: " + pathUtf8
                + " (cannot create its folder: " + ec.message() + ")");
            return false;
        }
    }

    // Open into a local stream first: a failed call leaves the current log
    // open, so the error line below still lands in it.
    std::ofstream stream(resolved, std::ios::app);
    if (!stream.is_open()) {
        log(LogLevel::Error, "Failed to open log file: " + pathUtf8);
        return false;
    }

    {
        // Swap under the lock: every line goes whole to the old file or to
        // the new one. Errors above are logged outside it (log() runs the
        // onLog listeners).
        TC_LOCK_GUARD(mutex_);
        closeFileLocked();
        fileStream_ = std::move(stream);
        filePath_ = pathUtf8;
    }
    return true;
}

namespace internal {
// Declared in tcThread.h, which is included before tcLog.h and cannot log.
void logThreadNotWaited() {
    // A global or static Thread still running at exit can be destroyed after
    // the Logger: skip the warning rather than log through a destroyed Logger.
    if (loggerDestroyed.load()) return;
    logWarning("Thread") << "destroyed while its thread was still running. "
                            "Call waitForThread() in the subclass destructor: the base "
                            "Thread destructor joins only after the subclass members "
                            "are destroyed";
}
} // namespace internal

// ---------------------------------------------------------------------------
// sokol -> Logger bridge (declared in tcLog.h)
// ---------------------------------------------------------------------------
namespace {
// Set while this thread logs a sokol panic (see internal::isLogNonBlocking).
thread_local bool logNonBlocking = false;
} // namespace

namespace internal {

bool isLogNonBlocking() {
    return logNonBlocking;
}

LogLevel sokolLogLevel(uint32_t logLevel) {
    switch (logLevel) {
        case 0:  return LogLevel::Fatal;     // panic
        case 1:  return LogLevel::Error;
        case 2:  return LogLevel::Warning;
        default: return LogLevel::Verbose;   // info: hidden by default
    }
}

std::string sokolLogMessage(const char* tag, uint32_t logItem,
                            const char* message, uint32_t lineNr) {
    std::string text = "[";
    text += tag ? tag : "sokol";
    text += "] ";
    if (message) {
        text += message;
    } else {
        // Release builds (no SOKOL_DEBUG) pass no message: the log item id
        // (SAPP_LOGITEM_*, SG_LOGITEM_*, ...) and sokol's source line.
        text += "id:" + std::to_string(logItem) + " line:" + std::to_string(lineNr);
    }
    return text;
}

void sokolLog(const char* tag, uint32_t logLevel, uint32_t logItem,
              const char* message, uint32_t lineNr, const char* filename,
              void* userData) {
    // Called from sokol's C code: nothing may throw out of here, and a panic
    // must reach slog_func (the abort) whatever happens before it.
    const bool noLogger = loggerDestroyed.load();
    if (!noLogger) {
        try {
            if (logLevel == 0) {
                // A panic: the process ends right after, so the sinks do not
                // wait for the lock (a thread holding it may never let go).
                struct NonBlocking {
                    NonBlocking() { logNonBlocking = true; }
                    ~NonBlocking() { logNonBlocking = false; }
                } nonBlocking;
                getLogger().log(LogLevel::Fatal,
                                sokolLogMessage(tag, logItem, message, lineNr));
            } else {
                getLogger().log(sokolLogLevel(logLevel),
                                sokolLogMessage(tag, logItem, message, lineNr));
            }
        } catch (...) {
        }
    }
    if (logLevel == 0 || noLogger) {
        // Panic: slog_func prints it too and aborts, as before the bridge.
        // After the Logger is gone (static destruction), slog_func alone.
        slog_func(tag, logLevel, logItem, message, lineNr, filename, userData);
    }
}

} // namespace internal

// ---------------------------------------------------------------------------
// Logger platform sink (declared in tcLog.h)
// ---------------------------------------------------------------------------
#if TC_LOG_SYSTEM_SINK
#if defined(__APPLE__) && !TARGET_OS_IPHONE
namespace {
// True when os_log lines are mirrored into the console that already shows
// stdout/stderr, so writing both would print each line twice there. Xcode
// sets OS_ACTIVITY_DT_MODE (libtrace then copies os_log to stderr) or, since
// Xcode 15, IDE_DISABLED_OS_ACTIVITY_DT_MODE (its console reads the unified
// log directly). libtrace mirrors whenever OS_ACTIVITY_DT_MODE is set, whatever
// its value ("NO", "0" and "" included; measured on macOS 26), so only its
// presence counts. Read once: a running app's environment does not change.
bool osLogMirroredToConsole() {
    static const bool mirrored =
        std::getenv("IDE_DISABLED_OS_ACTIVITY_DT_MODE") != nullptr ||
        std::getenv("OS_ACTIVITY_DT_MODE") != nullptr;
    return mirrored;
}
} // namespace
#endif

namespace internal {

void writeSystemLog(const LogEventArgs& e) {
#if defined(__APPLE__)
#if !TARGET_OS_IPHONE
    if (osLogMirroredToConsole()) return;
#endif
    static os_log_t osLog = os_log_create("org.trussc", "TrussC");
    os_log_type_t type;
    switch (e.level) {
        case LogLevel::Verbose: type = OS_LOG_TYPE_DEBUG; break;
        case LogLevel::Error:   type = OS_LOG_TYPE_ERROR; break;
        case LogLevel::Fatal:   type = OS_LOG_TYPE_FAULT; break;
        default:                type = OS_LOG_TYPE_DEFAULT; break;   // Notice, Warning
    }
    // %{public}: without it the unified log shows the text as <private>
    // outside a debugger.
    os_log_with_type(osLog, type, "[%{public}s] %{public}s",
                     logLevelToString(e.level), e.message.c_str());
#elif defined(_WIN32)
    // One call per line: each OutputDebugString call has a fixed cost (more
    // with a debugger or DebugView attached), so the whole line is built
    // first. The Logger has already applied the system level.
    std::string line;
    line.reserve(e.timestamp.size() + e.message.size() + 16);
    line += '[';
    line += e.timestamp;
    line += "] [";
    line += logLevelToString(e.level);
    line += "] ";
    line += e.message;
    line += '\n';
    // The wide call, so a debugger such as Visual Studio gets the UTF-16
    // text instead of bytes it reads as ANSI. DBWIN listeners (DebugView) get
    // it converted to the process code page, which is UTF-8 under TrussC's
    // manifest, so a viewer that reads the system ANSI code page (DebugView
    // on a Japanese system, say) still shows non-ASCII text garbled. Flags 0:
    // invalid UTF-8 becomes U+FFFD, nothing throws.
    int n = ::MultiByteToWideChar(CP_UTF8, 0, line.data(), (int)line.size(), nullptr, 0);
    if (n <= 0) return;
    std::wstring wide(n, L'\0');
    if (::MultiByteToWideChar(CP_UTF8, 0, line.data(), (int)line.size(), wide.data(), n) <= 0) return;
    OutputDebugStringW(wide.c_str());
#endif
}

} // namespace internal
#endif // TC_LOG_SYSTEM_SINK

// ---------------------------------------------------------------------------
// More one-per-process state (#249). Each of these used to be a function-local
// static or an inline variable in its header, which a Windows hot reload guest
// DLL duplicated: its recordings, beeps, console switch, main-thread queue,
// GPU releases, ... went into a copy the host's frame loop never looked at.
// ---------------------------------------------------------------------------

std::thread::id Thread::getMainThreadId() {
    static std::thread::id mainThreadId = std::this_thread::get_id();
    return mainThreadId;
}

namespace console {
namespace detail {
ThreadChannel<ConsoleEventArgs>& getChannel() {
    static ThreadChannel<ConsoleEventArgs> channel;
    return channel;
}
std::atomic<bool>& isRunning() {
    static std::atomic<bool> running{false};
    return running;
}
std::unique_ptr<std::thread>& getThread() {
    static std::unique_ptr<std::thread> t;
    return t;
}
} // namespace detail
} // namespace console

namespace internal {

#if !defined(__EMSCRIPTEN__)
ThreadChannel<std::function<void()>>& mainThreadQueue() {
    static ThreadChannel<std::function<void()>> q;
    return q;
}
std::atomic<size_t>& mainThreadQueuePendingCount() {
    static std::atomic<size_t> n{0};
    return n;
}
#endif

AsyncScheduler::AsyncScheduler() {
#ifdef _WIN32
    // Same convention as HeadlessSleeper: Windows before 10 1803 rejects
    // the high-resolution flag, leaving the condition-variable fallback.
    timer_ = CreateWaitableTimerExW(nullptr, nullptr, CREATE_WAITABLE_TIMER_HIGH_RESOLUTION,
                                    TIMER_MODIFY_STATE | SYNCHRONIZE);
    if (timer_) {
        taskEvent_ = CreateEventW(nullptr, FALSE, FALSE, nullptr);
        if (!taskEvent_) closeWaitHandles();
    }
#endif
    try {
        worker_ = std::thread([this] { run(); });
    } catch (...) {
        closeWaitHandles();
        throw;
    }
}

AsyncScheduler::~AsyncScheduler() {
    {
        std::lock_guard<std::mutex> lk(mtx_);
        stop_ = true;
        wakeWorker();
    }
    if (worker_.joinable()) worker_.join();
    closeWaitHandles();
}

void AsyncScheduler::closeWaitHandles() {
#ifdef _WIN32
    if (timer_) CloseHandle((HANDLE)timer_);
    if (taskEvent_) CloseHandle((HANDLE)taskEvent_);
    timer_ = taskEvent_ = nullptr;
#endif
}

void AsyncScheduler::wakeWorker() {
#ifdef _WIN32
    if (taskEvent_) SetEvent((HANDLE)taskEvent_);
#endif
    cv_.notify_all();
}

void AsyncScheduler::waitUntil(std::unique_lock<std::mutex>& lk, Clock::time_point when) {
#ifdef _WIN32
    if (timer_) {
        const auto remaining = when - Clock::now();
        if (remaining <= Clock::duration::zero()) return;
        // Relative, rounded up to 100 ns; a zero due time would mean an
        // absolute deadline in the past. The timer is armed under mtx_, so
        // changes after unlocking leave the auto-reset event signaled.
        using TimerTick = std::chrono::duration<int64_t, std::ratio<1, 10000000>>;
        LARGE_INTEGER due;
        due.QuadPart = -std::chrono::ceil<TimerTick>(remaining).count();
        if (SetWaitableTimer((HANDLE)timer_, &due, 0, nullptr, nullptr, FALSE)) {
            HANDLE handles[] = {(HANDLE)taskEvent_, (HANDLE)timer_};
            lk.unlock();
            const DWORD result = WaitForMultipleObjects(2, handles, FALSE, INFINITE);
            lk.lock();
            if (result == WAIT_OBJECT_0 || result == WAIT_OBJECT_0 + 1) return;
        }
        // Disable a failed native wait and re-evaluate the task list before
        // falling back: notifications could have arrived while unlocked.
        closeWaitHandles();
        return;
    }
#endif
    cv_.wait_until(lk, when);
}

AsyncScheduler& AsyncScheduler::get() {
    static AsyncScheduler instance;
    return instance;
}

uint64_t AsyncScheduler::newOwner() {
    static std::atomic<uint64_t> next{1};
    return next.fetch_add(1, std::memory_order_relaxed);
}

// Deferred GPU destroys (tcGpuDestroyQueue.h)
namespace {
struct PendingGpuDestroys {
    std::vector<sg_buffer>   buffers;
    std::vector<sg_image>    images;
    std::vector<sg_view>     views;
    std::vector<sg_sampler>  samplers;
    std::vector<sg_pipeline> pipelines;
    std::vector<sg_shader>   shaders;
};
// Leaked on purpose: resources held by statics (user globals, caches) release
// their handles from exit-time destructors, possibly after a function-local
// static queue would already be gone. Never destroying the queue keeps
// deferGpuDestroy() safe until the very end, as the inline vectors it replaces
// were (constant-initialized, so destroyed after everything built later).
PendingGpuDestroys& pendingGpuDestroys() {
    static PendingGpuDestroys* q = new PendingGpuDestroys();
    return *q;
}
} // anonymous namespace

void deferGpuDestroy(sg_buffer buf) {
    if (buf.id != 0) pendingGpuDestroys().buffers.push_back(buf);
}
void deferGpuDestroy(sg_image img) {
    if (img.id != 0) pendingGpuDestroys().images.push_back(img);
}
void deferGpuDestroy(sg_view view) {
    if (view.id != 0) pendingGpuDestroys().views.push_back(view);
}
void deferGpuDestroy(sg_sampler smp) {
    if (smp.id != 0) pendingGpuDestroys().samplers.push_back(smp);
}
void deferGpuDestroy(sg_pipeline pip) {
    if (pip.id != 0) pendingGpuDestroys().pipelines.push_back(pip);
}
void deferGpuDestroy(sg_shader shd) {
    if (shd.id != 0) pendingGpuDestroys().shaders.push_back(shd);
}

void drainPendingGpuDestroys() {
    auto& q = pendingGpuDestroys();
    if (sg_isvalid()) {
        for (sg_buffer buf : q.buffers)   sg_destroy_buffer(buf);
        for (sg_view view : q.views)      sg_destroy_view(view);
        for (sg_image img : q.images)     sg_destroy_image(img);
        for (sg_sampler smp : q.samplers) sg_destroy_sampler(smp);
        // Pipelines before shaders: a pipeline references its shader.
        for (sg_pipeline pip : q.pipelines) sg_destroy_pipeline(pip);
        for (sg_shader shd : q.shaders)     sg_destroy_shader(shd);
    }
    q.buffers.clear();
    q.images.clear();
    q.views.clear();
    q.samplers.clear();
    q.pipelines.clear();
    q.shaders.clear();
}

BeepManager& getManager() {
    static BeepManager manager;
    return manager;
}

ScreenRecorder& globalScreenRecorder() {
    static ScreenRecorder rec;
    return rec;
}

PbrPipeline& getPbrPipeline() {
    static PbrPipeline instance;
    return instance;
}

PointPipeline& getPointPipeline() {
    static PointPipeline instance;
    return instance;
}

// GPU caches whose contents nothing destroys (sokol_gl contexts, shaders,
// pipelines, samplers, font atlases). With a copy per module, every hot reload
// guest generation built and kept a new set in the host's sokol pools: FBO
// drawing stopped once sokol_gl's 4 context slots ran out, IBL bakes once the
// 32 shader slots did, and old generations' font atlases stayed resident.
std::unordered_map<uint64_t, FboSharedResources>& fboSharedMap() {
    static std::unordered_map<uint64_t, FboSharedResources> map;
    return map;
}

std::unordered_map<uint64_t, FboSharedMipResources>& fboSharedMipMap() {
    static std::unordered_map<uint64_t, FboSharedMipResources> map;
    return map;
}

IblBakeResources& iblBakeResources() {
    static IblBakeResources resources;
    return resources;
}

SharedFontCache& SharedFontCache::getInstance() {
    static SharedFontCache instance;
    return instance;
}

FontSamplers& fontSamplers() {
    static FontSamplers samplers;
    return samplers;
}

} // namespace internal

// ---------------------------------------------------------------------------
// Settings and registries that app code and host code share (#249): the main
// loop's rate and redraw requests, the projection defaults, the sokol_gl
// budget, touch-as-mouse, the data path root, the bitmap font atlas and its
// glyph registry, the overlay queries, the node and timer id sources, the
// debug counters, the current window context and the Apps attached to
// secondary windows. Each used to be an inline variable in its header, so a
// Windows hot reload guest's setFps(), redraw(), setDataPathRoot(),
// registerGlyph(), ... wrote a copy the host never read, the guest never saw
// what the host set, and an App whose window the host's close() released
// stayed attached in the guest's copy.
//
// Plain data (trivially destructible, constant-initialized) is a function-local
// static. Objects with a destructor are leaked on purpose: code running in
// exit-time destructors (an App saving its settings under getDataPath(), say)
// may reach them after a function-local static would already be destroyed,
// which the inline variables they replace, built before any app global, never
// were.
// ---------------------------------------------------------------------------
namespace internal {

MainLoopState& mainLoop() {
    static MainLoopState state;
    return state;
}

SglBudget& sglBudget() {
    static SglBudget budget;
    return budget;
}

BitmapFontAtlas& bitmapFontAtlas() {
    static BitmapFontAtlas atlas;
    return atlas;
}

bool& pixelPerfectMode() {
    static bool mode = false;
    return mode;
}

float& defaultScreenFov() {
    static float fovDeg = 45.0f;
    return fovDeg;
}

float& nearClipOverride() {
    static float dist = 0.0f;
    return dist;
}

float& farClipOverride() {
    static float dist = 0.0f;
    return dist;
}

bool& touchAsMouse() {
    static bool enabled = true;
    return enabled;
}

DataPathState& dataPathState() {
    static DataPathState* state = [] {
        auto* s = new DataPathState();
#ifdef __APPLE__
        s->root = "../../../data";
#else
        s->root = "data";
#endif
        return s;
    }();
    return *state;
}

std::function<bool()>& overlayHoveredQuery() {
    static auto* query = new std::function<bool()>();
    return *query;
}

std::function<bool()>& overlayFocusedQuery() {
    static auto* query = new std::function<bool()>();
    return *query;
}

uint64_t nextNodeInstanceId() {
    static std::atomic<uint64_t> next{0};
    return next.fetch_add(1, std::memory_order_relaxed);
}

// Node::callAfter() / callEvery() ids. As an inline static member, host code
// and a Windows hot reload guest each counted from 1 (and every reloaded guest
// again), so one node could hold two timers with the same id, and
// cancelTimer(id), which removes every timer with that id, cancelled both.
uint64_t nextNodeTimerId() {
    static std::atomic<uint64_t> next{1};
    return next.fetch_add(1, std::memory_order_relaxed);
}

// The debug counters behind getNodeCount() / getTextureCount() /
// getFboCount(). As inline variables, a Windows hot reload guest counted only
// the objects its own code created, and the host never saw them.
std::atomic<size_t>& nodeCount() {
    static std::atomic<size_t> count{0};
    return count;
}

std::atomic<size_t>& textureCount() {
    static std::atomic<size_t> count{0};
    return count;
}

std::atomic<size_t>& fboCount() {
    static std::atomic<size_t> count{0};
    return count;
}

namespace {
WindowContext* currentWindowCtxStorage = nullptr;
} // anonymous namespace

WindowContext*& currentWindowCtx() {
    return currentWindowCtxStorage;
}

WindowContext& currentWindowContext() {
    return currentWindowCtxStorage ? *currentWindowCtxStorage : mainWindowContext();
}

// Window::setApp() (app code) adds to it and the platform close() (host code)
// removes from it. Leaked like the ones above: ~Window() calls close(), and a
// Window an app keeps in a global is destroyed at exit.
std::unordered_set<const App*>& attachedApps() {
    static auto* apps = new std::unordered_set<const App*>();
    return *apps;
}

} // namespace internal

namespace bitmapfont {
namespace internal {

std::vector<StoredGlyph>& registry() {
    static auto* glyphs = new std::vector<StoredGlyph>();
    return *glyphs;
}

uint16_t& nextFreeCell() {
    static uint16_t cell = FIRST_REGISTERED_CELL;
    return cell;
}

uint64_t& registryVersion() {
    static uint64_t version = 0;
    return version;
}

} // namespace internal
} // namespace bitmapfont

} // namespace trussc
